import 'package:mobile_app/resources/resources.dart';

import 'beer.dart';

final List<Beer> beersForTestes = [
  Beer(
      name: "Centennial IPA",
      brewery: "Founders Brewing Co.",
      style: "IPA - American",
      abv: "7.2",
      ibu: "65",
      untappdRateCount: "2.023",
      untappdRating: "3.77"),
  Beer(
      name: "Зимняя Меланхолия (Winter Melancholy)",
      brewery: "AF Brew",
      style: "Porter - Imperial / Double Baltic",
      abv: "10.3",
      ibu: "30",
      untappdRateCount: "4.2",
      untappdRating: "4.05",
      image: AppImages.beerGreen),
  Beer(
      name: "Smoothie Mead: Mango, Orange",
      brewery: "Steppe & Wind Meadery (Степь и Ветер)",
      style: "Mead - Other",
      abv: "6",
      ibu: "0",
      untappdRateCount: "5",
      untappdRating: "4.18"),
  Beer(
      name: "Systems Overload In Incognito Mode",
      brewery: "Zagovor Brewery",
      style: "IPA - Triple New England",
      abv: "9.5",
      ibu: "45",
      untappdRateCount: "23",
      untappdRating: "4.25",
      image: AppImages.beerBlue),
  Beer(
      name: "Kentucky Brunch Brand Stout",
      brewery: "Toppling Goliath Brewing Co.",
      style: "Stout - Imperial / Double",
      abv: "12",
      ibu: "N/A",
      untappdRateCount: "2.781",
      untappdRating: "4.74"),
  Beer(
      name: "Systems Overload In Incognito Mode",
      brewery: "Zagovor Brewery",
      style: "IPA - Triple New England",
      abv: "9.5",
      ibu: "45",
      untappdRateCount: "23",
      untappdRating: "4.25"),
  Beer(
      name: "Blue Suede Shews",
      brewery: "Pips Meadery",
      style: "Mead - Other",
      abv: "14",
      ibu: "N/A",
      untappdRateCount: "1.924",
      untappdRating: "4.74",
      image: AppImages.beerBlue),
  Beer(
      name: "Systems Overload In Incognito Mode",
      brewery: "Zagovor Brewery",
      style: "IPA - Triple New England",
      abv: "9.5",
      ibu: "45",
      untappdRateCount: "23",
      untappdRating: "4.25",
      image: AppImages.beerBlue),
  Beer(
      name: "Rare Bourbon County Brand Stout (2010)",
      brewery: "Goose Island Beer Co.",
      style: "Stout - Imperial / Double",
      abv: "60",
      ibu: "13",
      untappdRateCount: "8.383",
      untappdRating: "4.74"),
  Beer(
      name: "Proprietor's Bourbon County Brand Stout (2014)",
      brewery: "Goose Island Beer Co.",
      style: "Stout - Imperial / Double",
      abv: "13.2",
      ibu: "N/A",
      untappdRateCount: "15.256",
      untappdRating: "4.74"),
];
